### PR TITLE
Adding qacc

### PR DESCRIPTION
**Pull request by blaiszik**

### CODE REVIEW

**Comment by arosen93** [comment]
Thanks for doing this! :)

**Comment by blaiszik** [comment]
Anytime! If you want to, pay it forward, see if you can find another resource to add. I'm going to add a bunch.

**Comment by arosen93** [comment]
Great idea! I have some in mind that I'll add later!

**Comment by rjacobs914** [comment]
Thanks Ben, for adding MAST-ML :)

**Review by blokhin — APPROVED** [review]

**Comment by blokhin** [comment]
@blaiszik @arosen93 @rjacobs914 many thanks, Gentlemen :+1:

**Pull request merged**
